### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by otanim** [iteratehackerspace/hyechat#40]
unfortunately [iteratechat](http://iteratechat.mybluemix.net) and [hyechat](hyechat.mybluemix.net) placed on the bluemix doesn't work. I suggest to move the server to [Heroku](heroku.com) as it easy to setup.

**Comment by fxfactorial** [comment]
Thanks! Yea, the bluemix trial was only 30 days. If you want to redeploy it to something else, feel free to!
